# Generated by Django 4.1 on 2022-09-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_online',
            field=models.BooleanField(default=True, help_text='话题是否在线'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=True, help_text='话题是否隐私'),
        ),
    ]
